#!/usr/bin/env sh

case $1 in
major|minor|patch) bump=$1 ;;
esac

if [ -z "$bump" ]; then
	echo "usage: $(basename $0) {major|minor|patch}"
	exit 1
fi

cd "$(dirname $0)"

if [ "$(git branch --show-current)" != main ]; then
	echo "must be on main branch"
	exit 1
elif ! git diff-index --quiet HEAD; then
	echo "uncommited changes"
	exit 1
fi

case $bump in
major) prog='
	/MAJOR/ { $2++; major = $2; print $1 "= " $2 }
	/MINOR/ { minor = 0; print $1 "= 0" }
	/PATCH/ { patch = 0; print $1 "= 0" }
' ;;
minor) prog='
	/MAJOR/ { major = $2 + 0; print $0 }
	/MINOR/ { $2++; minor = $2; print $1 "= " $2 }
	/PATCH/ { patch = 0; print $1 "= 0" }
';;
patch) prog='
	/MAJOR/ { major = $2 + 0; print $0 }
	/MINOR/ { minor = $2 + 0; print $0 }
	/PATCH/ { $2++; patch = $2; print $1 "= " $2 }
';;
esac

end='END { print major "." minor "." patch }'

file=src/bin/version.sml
z=$(awk -F '=' "$prog $end" < "$file")
ver="$(echo "$z" | tail -1)"
echo "$(echo "$z" | head -n -1)" > "$file"

git commit -am "v$ver"
git tag "v$ver"

echo "bumped to $ver"
